Parameters: 
  Region: 'cn-hangzhou'
  Name: 'key-auth-plugin'

SceneMetadata:
  Name:
    zh-cn: "key-auth 插件"
    en: "Key Auth Plugin"
  Description:
    zh-cn: "为云原生API网关提供基于API Key的认证和权限控制..."
    en: "Provides API Key-based authentication and authorization..."
  Logo: 'resources/icons/scene_logo.png'

SceneProfiles:
  - DisplayName:
      zh-cn: 单机版
      en: Single Service
    Template: 'templates/msa.yaml'
    Documentation:
      zh-cn: 'docs/zh-ch/index_ha.md'
      en: docs/en/index_ha_en.md
    Parameters: 
      Backend:
        Cpu: 1
        Memory: 4096
  - DisplayName:
      zh-cn: 高可用版
      en: High Availability
    Template: 'templates/msa-ha.yaml'
    Documentation:
      zh-cn: 'docs/zh-ch/index_ha.md'
      en: docs/en/index_ha_en.md