Status: Online
Score: 100
Categories: apigMatrix
Parameters: 
  Region: 'cn-hangzhou'
  Scence: 'msa'
ScenceInfos:
  - Locale: zh-CN
    Name: "Dify社区版"
    Description: "Dify.AI 是一款 LLMOps 平台，帮助开发者更简单、更快速地构建 AI 应用。它的核心理念是通过可声明式的 YAML 文件定义 AI 应用的各个方面，包括 Prompt、上下文和插件等。Dify 提供了可视化的 Prompt 编排、运营、数据集管理等功能。这些功能使得开发者能够在数天内完成 AI 应用的开发，或将 LLM 快速集成到现有应用中，并进行持续运营和改进，创造一个真正有价值的 AI 应用。"
    Image: 'resources/icons/service_logo.png'
ScenceConfigs:
  - Name: 单机版
    Url: 'templates/msa.yaml'
    DocumentUrl: 'docs/index.md'
    Parameters: 
      FcRuntime:
        Type: 'fc3'
        Content:
          Cpu: 2018
          Memory: 4096
  - Name: 高可用版
    Url: 'templates/msa-ha.yaml'
    DocumentUrl: 'docs/index_ha.md'