Parameters: 
  Region: 'cn-hangzhou'
  Name: 'key-auth-plugin'
  VpcId: 'vpc-cunbj26m1hkjrjddmljg'
SceneProfiles:
  - DisplayName:
      zh-cn: 单机版
      en: Single Service
    Template: 'templates/msa.yml'
    Parameters: 
      HttpApi:
        GatewayId: gw-cunbie6m1hkohjeuilrg
        EnvironmentId: env-cunbj26m1hkjrjddmljg
      Backend:
        Cpu: 1
        Memory: 4096
  - DisplayName:
      zh-cn: 高可用版
      en: High Availability
    Template: 'templates/msa-ha.yml'
    Parameters: 
      Backend:
        Cpu: 2
        Memory: 8192
