Parameters: 
  Region: 'cn-hangzhou'
  Name: 'key-auth-plugin'
ScenceConfigs:
  - Name: 单机版
    NameEn: 'Single Service'
    Url: 'templates/msa.yml'
    Parameters: 
      HttpApi:
        GatewayId: gw-cunbie6m1hkohjeuilrg
        EnvironmentId: env-cunbj26m1hkjrjddmljg
      Backend:
        Cpu: 2018
        Memory: 4096
  - Name: 高可用
    NameEn: 'High Availability'
    Url: 'templates/msa-ha.yml'
    Parameters: 
      Backend:
        Cpu: 4096
        Memory: 8192
