name: publish package to registry

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: git config --global core.symlinks false
        shell: bash
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make jq curl wget
      - name: Zip Files
        run: |
          zip -r "$(basename "$PWD").zip" . -x ".github/*"
      - name: Publish to OSS
        run: |
          npx msa-tool upload $(basename "$PWD").zip
      # - name: generate publish.yaml
      #   run: |
      #     npx msa-tool publish
      # - name: install s
      #   run: |
      #     npm i @serverless-devs/s@3.1.3 -g
      # - name: s registry login
      #   run: |
      #     s registry login --token ${{ secrets.ALIBABA_REGISTRY_V3_PUBLISH_TOKEN }}
      # - name: release prod
      #   run: |
      #     s registry publish
